
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class DailyDet extends javax.swing.JFrame {
Connection connection=null;
PreparedStatement ps=null;
ResultSet rs=null;
String filePath=null;
    /**
     * Creates new form DailyDet
     */
    public DailyDet() {
        initComponents();
        currentTimeDate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_Date1 = new javax.swing.JLabel();
        jLabel_Date = new javax.swing.JLabel();
        jLabel_Date2 = new javax.swing.JLabel();
        jLabel_Time = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSearch = new javax.swing.JButton();
        jTextField_employeeNo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField_firstName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_surName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_today = new javax.swing.JTextField();
        jButton_exit1 = new javax.swing.JButton();
        jButton_exit3 = new javax.swing.JButton();
        jButton_exit2 = new javax.swing.JButton();
        jButton_exit4 = new javax.swing.JButton();
        jButton_exit5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("BARAKA ROSES");

        jLabel_Date1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel_Date1.setText("Current Date");

        jLabel_Date.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        jLabel_Date2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel_Date2.setText("Current Time");

        jLabel_Time.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Daily Information Update");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("EmployeeNo.");

        jSearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jSearch.setText("Look Up");
        jSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchActionPerformed(evt);
            }
        });

        jTextField_employeeNo.setBackground(new java.awt.Color(102, 255, 102));
        jTextField_employeeNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_employeeNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_employeeNoActionPerformed(evt);
            }
        });
        jTextField_employeeNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_employeeNoKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("First Name");

        jTextField_firstName.setEditable(false);
        jTextField_firstName.setBackground(new java.awt.Color(102, 255, 102));
        jTextField_firstName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_firstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_firstNameKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Surname");

        jTextField_surName.setEditable(false);
        jTextField_surName.setBackground(new java.awt.Color(102, 255, 102));
        jTextField_surName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_surName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_surNameKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Hours Worked Today");

        jTextField_today.setBackground(new java.awt.Color(102, 255, 102));
        jTextField_today.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_today.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_todayKeyTyped(evt);
            }
        });

        jButton_exit1.setBackground(new java.awt.Color(102, 0, 102));
        jButton_exit1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_exit1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_exit1.setText("Update Details");
        jButton_exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_exit1ActionPerformed(evt);
            }
        });

        jButton_exit3.setBackground(new java.awt.Color(102, 0, 102));
        jButton_exit3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_exit3.setForeground(new java.awt.Color(255, 255, 255));
        jButton_exit3.setText("Main Menu");
        jButton_exit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_exit3ActionPerformed(evt);
            }
        });

        jButton_exit2.setBackground(new java.awt.Color(102, 0, 102));
        jButton_exit2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_exit2.setForeground(new java.awt.Color(255, 255, 255));
        jButton_exit2.setText("Back");
        jButton_exit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_exit2ActionPerformed(evt);
            }
        });

        jButton_exit4.setBackground(new java.awt.Color(102, 0, 102));
        jButton_exit4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_exit4.setForeground(new java.awt.Color(255, 255, 255));
        jButton_exit4.setText("Exit");
        jButton_exit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_exit4ActionPerformed(evt);
            }
        });

        jButton_exit5.setBackground(new java.awt.Color(102, 0, 102));
        jButton_exit5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_exit5.setForeground(new java.awt.Color(255, 255, 255));
        jButton_exit5.setText("Salary Details");
        jButton_exit5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_exit5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_exit1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jButton_exit3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_exit5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_exit2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_exit4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_Date1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel_Date2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel_Time, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(159, 159, 159))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField_today, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField_surName, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(59, 59, 59)
                                    .addComponent(jTextField_employeeNo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(jSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Date1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Date2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Time, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_employeeNo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_surName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_today, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_exit1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_exit3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_exit4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_exit5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_exit2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void currentTimeDate(){
        Thread clock=new Thread(){
        public void run(){
            for(;;){
                Calendar cal=new GregorianCalendar();
    int second=cal.get(Calendar.SECOND);
    int minute=cal.get(Calendar.MINUTE);
    int hour=cal.get(Calendar.HOUR); 
    jLabel_Time.setText(+hour+":"+minute+":"+second);
    
    
    int day=cal.get(Calendar.DAY_OF_MONTH);
    int month=cal.get(Calendar.MONTH);
    int year=cal.get(Calendar.YEAR); 
    jLabel_Date.setText(+year+"-"+(month+1)+"-"+day);
     try{
         sleep (1000);  
    }catch (InterruptedException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        }
        };
        clock.start();
    }
 public void theQuery(String query){
        Connection con=null;
        Statement st=null;
        try{
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/finance","root","");
            st=con.createStatement();
            st.executeUpdate(query);
            JOptionPane.showMessageDialog(null,"Records Updated");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }
 public void add(String query){
        Connection con=null;
        Statement st=null;
        try{
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/finance","root","");
            st=con.createStatement();
            st.executeUpdate(query);
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }
public void Update(String query){
        Connection con=null;
        Statement st=null;
        try{
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/finance","root","");
            st=con.createStatement();
            st.executeUpdate(query);
            JOptionPane.showMessageDialog(null,"Records Updated");
            add("update pickup set todayHours='"+jTextField_today.getText()+"' where employeeNo="+jTextField_employeeNo.getText());
            add("update pickup set hoursWorked=hoursWorked+todayHours where employeeNo="+jTextField_employeeNo.getText());
            add("update pickup set periodofEmployee=periodofEmployee+todayHours where employeeNo="+jTextField_employeeNo.getText());
            add("update pickup set salary=hoursWorked*rate where employeeNo="+jTextField_employeeNo.getText());
            add("update pickup set advance=salary/4 where employeeNo="+jTextField_employeeNo.getText());
            add("update pickup set medCover=salary*1.5 where employeeNo="+jTextField_employeeNo.getText());
            add("update pickup set bonus=salary*0.2 where employeeNo="+jTextField_employeeNo.getText());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }
    private void jSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchActionPerformed
        String un=jTextField_employeeNo.getText();
        Connection conn=null;
        PreparedStatement pstmt=null;
        ResultSet rs=null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/finance","root","");
            pstmt=conn.prepareStatement("select* from pickup where employeeNo=?");

            pstmt.setString(1,un);
            rs=pstmt.executeQuery();
            while(rs.next()){
                jTextField_surName.setText(rs.getString("surName"));
                jTextField_firstName.setText(rs.getString("firstName"));
try
    
{

if(un.length()>0)
{
    Class.forName("com.mysql.jdbc.Driver");
connection=DriverManager.getConnection("jdbc:mysql://localhost:3306/finance", "root", "");
ps=connection.prepareStatement("select * from image where id=?");
ps.setObject(1, un);
rs=ps.executeQuery();
byte b[] = null;
while(rs.next())
{
b= rs.getBytes(2);
}

jLabel5.setIcon(new ImageIcon (Toolkit.getDefaultToolkit().createImage(b)));


}else
{
JOptionPane.showMessageDialog(this,"Please enter EmployeeNo..." );
}


}catch(Exception e)
{

}

            
            
            
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        finally{
            try{
                conn.close();
                pstmt.close();
                rs.close();
            }
            catch(Exception e){
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jSearchActionPerformed

    private void jTextField_employeeNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_employeeNoActionPerformed

    }//GEN-LAST:event_jTextField_employeeNoActionPerformed

    private void jTextField_employeeNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_employeeNoKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c)||(c==KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE))){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_employeeNoKeyTyped

    private void jTextField_firstNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_firstNameKeyTyped
        char c=evt.getKeyChar();
        if(!(c>=KeyEvent.VK_A&&c<=KeyEvent.VK_Z  )||(c==KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE)||(c==KeyEvent.VK_CAPS_LOCK)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_firstNameKeyTyped

    private void jTextField_surNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_surNameKeyTyped
        char c=evt.getKeyChar();
        if(!(c>=KeyEvent.VK_A&&c<=KeyEvent.VK_Z  )||(c==KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE)||(c==KeyEvent.VK_CAPS_LOCK)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_surNameKeyTyped

    private void jTextField_todayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_todayKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c)||(c==KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE))){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_todayKeyTyped

    private void jButton_exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_exit1ActionPerformed
        Update("insert into daily (empNo,firstName,surName,hoursofWork,date) values ('"+jTextField_employeeNo.getText()+"','"+jTextField_firstName.getText()+"','"+jTextField_surName.getText()+"','"+jTextField_today.getText()+"','"+jLabel_Date.getText()+"')");
    }//GEN-LAST:event_jButton_exit1ActionPerformed

    private void jButton_exit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_exit3ActionPerformed
        new welcome().setVisible(true);
        this.setVisible(false);;

    }//GEN-LAST:event_jButton_exit3ActionPerformed

    private void jButton_exit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_exit2ActionPerformed
         new welcome().setVisible(true);
        this.setVisible(false);;
    }//GEN-LAST:event_jButton_exit2ActionPerformed

    private void jButton_exit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_exit5ActionPerformed
        SalaryDetails Info= new SalaryDetails();
        Info.setVisible(true);
    }//GEN-LAST:event_jButton_exit5ActionPerformed

    private void jButton_exit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_exit4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton_exit4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DailyDet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_exit1;
    private javax.swing.JButton jButton_exit2;
    private javax.swing.JButton jButton_exit3;
    private javax.swing.JButton jButton_exit4;
    private javax.swing.JButton jButton_exit5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Date;
    private javax.swing.JLabel jLabel_Date1;
    private javax.swing.JLabel jLabel_Date2;
    private javax.swing.JLabel jLabel_Time;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jSearch;
    private javax.swing.JTextField jTextField_employeeNo;
    private javax.swing.JTextField jTextField_firstName;
    private javax.swing.JTextField jTextField_surName;
    private javax.swing.JTextField jTextField_today;
    // End of variables declaration//GEN-END:variables
}
